language: C
sudo: enabled
addons:
  apt:
    update: true
    packages:
      - libssl-dev
  homebrew:
    packages:
      - openssl

matrix:
  include:
#    - os: linux
#      dist: xenial
#      addons:
#        apt:
#          packages:
#            - libsystemd-dev
#      before_script:
#        - ./bootstrap
#      script:
#        - ./configure --enable-intf-dummy --enable-intf-dbus
#        - make
#        - sudo make install
#    - os: linux
#      dist: trusty
#      before_script:
#        - ./bootstrap
#      script:
#        - ./configure --enable-intf-dummy
#        - make
#        - sudo make install
#    - os: osx
#      osx_image: xcode10.2
#      before_script:
#        - ./bootstrap
#      script:
#        - ./configure --enable-intf-dummy
#        - make
#        - sudo make install
    - os: windows
      before_install:
        - |-
          choco uninstall -y mingw
          choco install --no-progress -y cygwin --params "-q --disable-buggy-antivirus --upgrade-also --wait --arch=x86_64 --root=C:\tools\cygwin --packages=wget,bash,p7zip,libssl-devel,git,gcc-core,make,diffutils,autoconf,automake,m4,libtool,libncurses-devel,libreadline-devel --verbose --no-admin"
          export PATH=/c/tools/cygwin/bin:/c/tools/cygwin/usr/bin:$PATH
          echo PATH is ${PATH}

      cache:
        directories:
        - $HOME/AppData/Local/Temp/chocolatey
        - /C/tools/cygwin

      before_script:
        - ./bootstrap

      script:
        - ./configure IANADIR="./" IANAUSERDIR="./" DEFAULT_INTF="lanplus" --enable-intf-lan --enable-intf-lanplus --disable-intf-bmc --disable-intf-free --disable-intf-open --disable-intf-imb --disable-intf-usb --enable-intf-serial --enable-ipmishell
        - make

